In [20]:
import pandas as pd
import numpy

In [21]:
from time import gmtime, strftime

In [22]:
def getLeagueTable():
    leagueTable = pd.read_html(io="https://www.bbc.co.uk/sport/football/premier-league/table")
    leagueTable = leagueTable[0]
    leagueTable.rename(columns = {'Unnamed: 0':'Position'}, inplace = True)
    leagueTable2 = leagueTable[['Team', 'Position', 'Pts']]
    leagueTable3 = leagueTable2[leagueTable2['Team'].notnull()]
    leagueTable3 = leagueTable3.astype( {"Position": int, "Pts": int} )
    leagueTable3['PositionDate'] = strftime("%Y-%m-%d", gmtime())
    return leagueTable3

In [23]:
leagueTable = getLeagueTable()

In [27]:
leagueTable

              Team  Position  Pts PositionDate
0         Man City         1   74   2019-03-12
1        Liverpool         2   73   2019-03-12
2        Tottenham         3   61   2019-03-12
3          Arsenal         4   60   2019-03-12
4          Man Utd         5   58   2019-03-12
5          Chelsea         6   57   2019-03-12
6           Wolves         7   44   2019-03-12
7          Watford         8   43   2019-03-12
8         West Ham         9   39   2019-03-12
9        Leicester        10   38   2019-03-12
10         Everton        11   37   2019-03-12
11     Bournemouth        12   37   2019-03-12
12       Newcastle        13   34   2019-03-12
13  Crystal Palace        14   33   2019-03-12
14        Brighton        15   33   2019-03-12
15     Southampton        16   30   2019-03-12
16         Burnley        17   30   2019-03-12
17         Cardiff        18   28   2019-03-12
18          Fulham        19   17   2019-03-12
19    Huddersfield        20   14   2019-03-12